"""DSP filters for sEMG signal preprocessing.

All functions operate on numpy arrays.

PHYSIOLOGICAL RATIONALE FOR FILTER PARAMETERS:
Traditional electromyography (EMG) used in physical prosthetics and active gesture recognition typically
utilizes a bandpass filter from 20 Hz to 450 Hz. This bandwidth is chosen to capture high-speed motor unit action
potentials (MUAPs) generated by large skeletal muscle contractions (e.g., bicep flexion) while rejecting movement
artifacts (which lie below 10–20 Hz).

However, for silent speech interface (SSI) surface electromyography (sEMG) around the vocal tract, jaw, and throat:
1. **Low-Velocity Articulatory Movements**: The vocal articulators (tongue, throat musculature, jaw) move at low speeds,
   producing slow neuromuscular signal envelopes (1–15 Hz) during internal speech imagery/subvocalization.
2. **Rejection of Speech Dynamics**: Standard acoustic speech features operate at higher frequency bands, but silent
   neuromuscular activations are primary envelope-based targets.
3. **Powerline Interference Gating**: Powerline noise (50 Hz in EU, 60 Hz in US) heavily corrupts biological signals.
   By constraining the bandpass filter's upper bound to 50.0 Hz, we inherently reject the majority of powerline
   interference before it can leak into feature extractors.
4. **Nyquist Limit Constraints**: Wearable device power budgets restrict hardware sampling rates (typically 250 Hz).
   At fs=250 Hz, the Nyquist limit is 125 Hz. A filter cutoff of 50 Hz ensures we satisfy the Nyquist-Shannon sampling
   theorem with a generous guard band, avoiding aliasing artifacts.

Therefore, we implement and default to the AlterEgo-inspired 1.3–50.0 Hz bandpass filter, but support standard
20–450.0 Hz ranges via parameter config.
"""

import numpy as np
from scipy.signal import butter, filtfilt, iirnotch


def remove_dc(signal: np.ndarray, window_samples: int = 250) -> np.ndarray:
    """Remove DC offset by subtracting a rolling mean.

    Args:
        signal: 1D array of samples for a single channel.
        window_samples: Window size in samples (default 250 = 1s at 250Hz).

    Returns:
        DC-removed signal.
    """
    if len(signal) < window_samples:
        return signal - np.mean(signal)

    # Use cumsum trick for fast rolling mean
    cumsum = np.cumsum(signal)
    cumsum = np.insert(cumsum, 0, 0)
    rolling_mean = np.empty_like(signal)

    for i in range(len(signal)):
        start = max(0, i - window_samples + 1)
        rolling_mean[i] = (cumsum[i + 1] - cumsum[start]) / (i - start + 1)

    return signal - rolling_mean


def bandpass(
    signal: np.ndarray,
    fs: float = 250.0,
    low: float = 1.3,
    high: float = 50.0,
    order: int = 4,
) -> np.ndarray:
    """Butterworth bandpass filter for raw sEMG.

    Args:
        signal: 1D array of samples.
        fs: Sampling frequency in Hz.
        low: Low cutoff frequency.
        high: High cutoff frequency.
        order: Filter order.

    Returns:
        Bandpass-filtered signal.
    """
    nyq = fs / 2.0
    low_norm = low / nyq
    # Clamp upper bound to slightly below Nyquist to prevent unstable filter coefficients
    high_norm = min(high / nyq, 0.99)

    if low_norm >= high_norm or low_norm <= 0:
        return signal  # Return unfiltered if bounds are invalid

    b, a = butter(order, [low_norm, high_norm], btype='band')
    return filtfilt(b, a, signal).astype(signal.dtype)


def notch_60hz(
    signal: np.ndarray,
    fs: float = 250.0,
    freq: float = 60.0,
    Q: float = 30.0,
) -> np.ndarray:
    """Notch filter to remove power line interference.

    Args:
        signal: 1D array of samples.
        fs: Sampling frequency.
        freq: Notch frequency (60 Hz US, 50 Hz EU).
        Q: Quality factor (higher = narrower notch).

    Returns:
        Notch-filtered signal.
    """
    if freq >= fs / 2:
        return signal  # Can't notch at or above Nyquist

    b, a = iirnotch(freq, Q, fs)
    return filtfilt(b, a, signal).astype(signal.dtype)


def smooth(signal: np.ndarray, window: int = 3) -> np.ndarray:
    """Simple moving average smoothing.

    Args:
        signal: 1D array of samples.
        window: Window size in samples.

    Returns:
        Smoothed signal.
    """
    if window <= 1 or len(signal) < window:
        return signal

    kernel = np.ones(window) / window
    return np.convolve(signal, kernel, mode='same')


def preprocess_channel(
    signal: np.ndarray,
    fs: float = 250.0,
    low: float = 1.3,
    high: float = 50.0,
    apply_bandpass: bool = True,
    apply_notch: bool = True,
) -> np.ndarray:
    """Full preprocessing pipeline for a single channel.

    Args:
        signal: 1D float array of raw ADC values.
        fs: Sample rate.
        low: Low cutoff frequency for bandpass.
        high: High cutoff frequency for bandpass.
        apply_bandpass: Whether to apply bandpass.
        apply_notch: Whether to apply notch filter.

    Returns:
        Preprocessed signal.
    """
    sig = signal.astype(np.float64)
    sig = remove_dc(sig, window_samples=int(fs))

    if apply_bandpass:
        sig = bandpass(sig, fs=fs, low=low, high=high)

    if apply_notch:
        # Check notch frequency based on config, filter it if it's below Nyquist
        sig = notch_60hz(sig, fs=fs, freq=60.0)

    sig = smooth(sig, window=3)
    return sig


def preprocess_multichannel(
    data: np.ndarray,
    fs: float = 250.0,
    low: float = 1.3,
    high: float = 50.0,
    apply_bandpass: bool = True,
    apply_notch: bool = True,
) -> np.ndarray:
    """Preprocess all channels.

    Args:
        data: 2D array of shape (num_samples, num_channels).
        fs: Sample rate.
        low: Low cutoff frequency for bandpass.
        high: High cutoff frequency for bandpass.

    Returns:
        Preprocessed data of same shape.
    """
    result = np.empty_like(data, dtype=np.float64)
    for ch in range(data.shape[1]):
        result[:, ch] = preprocess_channel(
            data[:, ch],
            fs=fs,
            low=low,
            high=high,
            apply_bandpass=apply_bandpass,
            apply_notch=apply_notch,
        )
    return result
